### ISSUE TITLE
Keyboard doesn't open when focusing on a <gaia-text-input>

### ISSUE THREAD

**Issue by DouglasSherk** [fxos-components/fxos-text-input#2]
See https://github.com/fxos/sharing

I don't have a reduced test case, but I think this app is sufficient as I have a working counterexample. The example page, http://gaia-components.github.io/gaia-text-input/ is currently busted, so if you fix that, then I'll use that to reduce it for you.

STR:
1. Tap on "Share My Apps"
2. Tap on "Rename Device"
3. A prompt will pop up with a text field. Tap on it.
Expected: Keyboard comes up.
Actual: No keyboard will come up.

Notes: If you replace this `<gaia-text-input>` element with an `<input>`, it will work as expected.

**Comment by DouglasSherk** [comment]
Note that this may have something to do with being embedded in `<gaia-dialog>`, or perhaps even more broadly, other web components. I haven't reduced that to see. The fixed example page will tell us for sure.

**Comment by wilsonpage** [comment]
Example page is now working. I found [bug 1079236](https://bugzilla.mozilla.org/show_bug.cgi?id=1079236) which I filed a couple of months ago.

**Comment by wilsonpage** [comment]
Not sure if this is a Gecko or Gaia bug.
